version: 2
jobs:
  build-php56:
    steps:
      - checkout
      - run: docker-compose up -d php56
      - run: make test_php56
  build-php70:
    steps:
      - checkout
      - run: docker-compose up -d php70
      - run: make test_php70
  build-php71:
    steps:
      - checkout
      - run: docker-compose up -d php71
      - run: make test_php71
  build-php72:
    steps:
      - checkout
      - run: docker-compose up -d php72
      - run: make test_php72
workflows:
  version: 2
  build:
    jobs:
      - build-php56
      - build-php70
      - build-php71
      - build-php72
