version: 2
jobs:
  build-php56:
    working_directory: /php
    docker:
      - image: tomohiroukawa/php-cli:5.6
    steps:
      - checkout

      - run:
          name: Run test
          command: |
            composer install
            make test

  build-php70:
    working_directory: /php
    docker:
      - image: tomohiroukawa/php-cli:7.0
    steps:
      - checkout

      - run:
          name: Run test
          command: |
            composer install
            make test

  build-php71:
    working_directory: /php
    docker:
      - image: tomohiroukawa/php-cli:7.1
    steps:
      - checkout

      - run:
          name: Run test
          command: |
            composer install
            make test

  build-php72:
    working_directory: /php
    docker:
      - image: tomohiroukawa/php-cli:7.2
    steps:
      - checkout

      - run:
          name: Run test
          command: |
            composer install
            make test

workflows:
  version: 2
  build:
    jobs:
      - build-php56
      - build-php70
      - build-php71
      - build-php72
